name: dangdays
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: 2.0.0-alpha-33
  bootstrap: any
  browser: '>=0.10.0 <0.11.0'
  jquery_for_pub: any
  test: any
transformers:
- angular2:
    entry-points: web/main.dart
